language: ruby

os:
  - linux
  - osx

rvm:
  - ruby-head
  - 2.3
  - 2.2
  - jruby-head
  - jruby-9.1

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.1

notifications:
  email: false

install:
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec gem build transmission-rss.gemspec
  - bundle exec rake
