language: ruby

os:
  - linux
  - osx

rvm:
  - ruby-head
  - 2.4
  - 2.1
  - 1.9
  - jruby

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: 1.9
    - rvm: jruby
  exclude:
    - os: osx
      rvm: ruby-head
    - os: osx
      rvm: 2.1
    - os: osx
      rvm: 1.9
    - os: osx
      rvm: jruby

notifications:
  email: false

install:
  - gem install bundler
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec gem build transmission-rss.gemspec
  - bundle exec rake
