language: ruby

os:
  - linux
  - osx

rvm:
  - ruby-head
  - 2.3.0
  - 2.2.4
  - jruby-9.0.5.0

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - rvm: jruby-9.0.5.0

notifications:
  email: false

script:
  - bundle exec gem build transmission-rss.gemspec
  - bundle exec rake
